services:
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    volumes:
      - 'sail-meilisearch:/meili_data'
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://127.0.0.1:7700/health'
      retries: 3
      timeout: 5s

  nominatim:
    image: mediagis/nominatim:4.4
    ports:
      - '${FORWARD_NOMINATIM_PORT:-8080}:8080'
    environment:
      PBF_URL: 'https://download.geofabrik.de/europe/romania-latest.osm.pbf'
      REPLICATION_URL: 'https://download.geofabrik.de/europe/romania-updates'
      REPLICATION_UPDATE_INTERVAL: 86400
      REPLICATION_RECHECK_INTERVAL: 900
      UPDATE_MODE: catch-up

      POSTGRES_SHARED_BUFFERS: '2GB'
      POSTGRES_MAINTAINENCE_WORK_MEM: '10GB'
      POSTGRES_AUTOVACUUM_WORK_MEM: '2GB'
      POSTGRES_WORK_MEM: '50MB'
      POSTGRES_EFFECTIVE_CACHE_SIZE: '24GB'
      POSTGRES_SYNCHRONOUS_COMMIT: 'off'
      POSTGRES_MAX_WAL_SIZE: '1GB'
      POSTGRES_CHECKPOINT_TIMEOUT: '10min'
      POSTGRES_CHECKPOINT_COMPLETITION_TARGET: '0.9'
    volumes:
      - 'sail-nominatim:/var/lib/postgresql/14/main'

volumes:
  sail-meilisearch:
    driver: local
  sail-nominatim:
    driver: local
