/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id"
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key"
        },
        {
            "name": "tags"
        }
    ],
    "filament.admin.auth.login": [],
    "filament.admin.auth.logout": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.resources.duplicates.index": [],
    "filament.admin.resources.imports.index": [],
    "filament.admin.resources.imports.create": [],
    "filament.admin.resources.imports.view_report": [
        {
            "name": "record"
        }
    ],
    "filament.admin.resources.issues.index": [],
    "filament.admin.resources.issues.create": [],
    "filament.admin.resources.issues.edit": [
        {
            "name": "record"
        }
    ],
    "filament.admin.resources.issues.view": [
        {
            "name": "record"
        }
    ],
    "filament.admin.resources.map-points.index": [],
    "filament.admin.resources.map-points.create": [],
    "filament.admin.resources.map-points.edit": [
        {
            "name": "record"
        }
    ],
    "filament.admin.resources.map-points.view": [
        {
            "name": "record"
        }
    ],
    "filament.admin.resources.permissions.index": [],
    "filament.admin.resources.permissions.create": [],
    "filament.admin.resources.permissions.edit": [
        {
            "name": "record"
        }
    ],
    "filament.admin.resources.recycle-materials.index": [],
    "filament.admin.resources.recycle-materials.create": [],
    "filament.admin.resources.recycle-materials.edit": [
        {
            "name": "record"
        }
    ],
    "filament.admin.resources.reports.index": [],
    "filament.admin.resources.reports.saved": [],
    "filament.admin.resources.reports.view": [
        {
            "name": "record"
        }
    ],
    "filament.admin.resources.roles.index": [],
    "filament.admin.resources.roles.create": [],
    "filament.admin.resources.roles.edit": [
        {
            "name": "record"
        }
    ],
    "filament.admin.resources.users.index": [],
    "filament.admin.resources.users.create": [],
    "filament.admin.resources.users.edit": [
        {
            "name": "record"
        }
    ],
    "sanctum.csrf-cookie": [],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename"
        }
    ],
    "filament-excel-download": [
        {
            "name": "path"
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "map-points.validate": [
        {
            "name": "point_id"
        }
    ],
    "map_points.map-view": [
        {
            "name": "point"
        }
    ],
    "import.xlsx-example": []
}
}
export {};
